"""Add selfeval_json to sessions

Revision ID: 1e8eff13d73f
Revises: b8220fa8efff
Create Date: 2025-08-26 20:34:43.741046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e8eff13d73f"
down_revision: Union[str, None] = "b8220fa8efff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("selfeval_json", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "selfeval_json")
    # ### end Alembic commands ###
