"""Add gender, age, education to sessions

Revision ID: 6c9880b00e5c
Revises: d183fc068c61
Create Date: 2025-08-24 12:13:55.374738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c9880b00e5c"
down_revision: Union[str, None] = "d183fc068c61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("gender", sa.String(), nullable=True))
    op.add_column("sessions", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column("sessions", sa.Column("education", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "education")
    op.drop_column("sessions", "age")
    op.drop_column("sessions", "gender")
    # ### end Alembic commands ###
