"""Add completed flag to sessions

Revision ID: b8220fa8efff
Revises: 6c9880b00e5c
Create Date: 2025-08-24 13:35:38.039622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b8220fa8efff"
down_revision: Union[str, None] = "6c9880b00e5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "completed", sa.Boolean(), nullable=False, server_default=sa.text("0")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "completed")
    # ### end Alembic commands ###
