"""Remove gender, age, education from sessions

Revision ID: c59ae0f5d98a
Revises: 1e8eff13d73f
Create Date: 2025-08-26 21:29:46.828169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59ae0f5d98a'
down_revision: Union[str, None] = '1e8eff13d73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.drop_column('sessions', 'education')
    op.drop_column('sessions', 'gender')
    op.drop_column('sessions', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('age', sa.INTEGER(), nullable=True))
    op.add_column('sessions', sa.Column('gender', sa.VARCHAR(), nullable=True))
    op.add_column('sessions', sa.Column('education', sa.VARCHAR(), nullable=True))
    op.alter_column('sessions', 'uuid',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
