"""add master_image to exhibits

Revision ID: c8831cbb50b0
Revises: c59ae0f5d98a
Create Date: 2025-08-29 10:24:20.991997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8831cbb50b0"
down_revision: Union[str, None] = "c59ae0f5d98a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exhibits", sa.Column("master_image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exhibits", "master_image")
    # ### end Alembic commands ###
