"""add_last_activity_to_sessions

Revision ID: f2569b17d301
Revises: f407fbafc990
Create Date: 2025-09-02 09:52:33.737976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2569b17d301'
down_revision: Union[str, None] = 'f407fbafc990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_exhibit_slug_language'), 'exhibits', type_='unique')
    op.create_index(op.f('ix_exhibits_slug'), 'exhibits', ['slug'], unique=False)
    op.add_column('sessions', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'last_activity')
    op.drop_index(op.f('ix_exhibits_slug'), table_name='exhibits')
    op.create_unique_constraint(op.f('uq_exhibit_slug_language'), 'exhibits', ['slug', 'language'])
    # ### end Alembic commands ###
