"""add_last_activity_to_sessions

Revision ID: f2569b17d301
Revises: f407fbafc990
Create Date: 2025-09-02 09:52:33.737976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2569b17d301'
down_revision: Union[str, None] = 'f407fbafc990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibits', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('uq_exhibit_slug_language'), type_='unique')
        batch_op.create_index(batch_op.f('ix_exhibits_slug'), ['slug'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('last_activity')

    with op.batch_alter_table('exhibits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exhibits_slug'))
        batch_op.create_unique_constraint(batch_op.f('uq_exhibit_slug_language'), ['slug', 'language'])
    # ### end Alembic commands ###
