"""Add language support

Revision ID: f407fbafc990
Revises: 
Create Date: 2025-09-01 20:58:01.826910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f407fbafc990'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exhibits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=False, server_default='cz'))
        batch_op.create_index(batch_op.f('ix_exhibits_language'), ['language'], unique=False)
        batch_op.drop_index('ix_exhibits_slug')
        batch_op.create_unique_constraint('uq_exhibit_slug_language', ['slug', 'language'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sessions_language'), ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_language'))
        batch_op.drop_column('language')

    with op.batch_alter_table('exhibits', schema=None) as batch_op:
        batch_op.drop_constraint('uq_exhibit_slug_language', type_='unique')
        batch_op.create_index('ix_exhibits_slug', ['slug'], unique=1)
        batch_op.drop_index(batch_op.f('ix_exhibits_language'))
        batch_op.drop_column('language')
    # ### end Alembic commands ###
