"""add exhibition feedback json field

Revision ID: f69b7d0c47c6
Revises: f2569b17d301
Create Date: 2025-09-08 13:44:09.558230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69b7d0c47c6'
down_revision: Union[str, None] = 'f2569b17d301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('exhibition_feedback_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'exhibition_feedback_json')
    # ### end Alembic commands ###
